export const cruiseData = {
  hero: {
    kicker: "HANDPICKED CRUISES · PRIVATE HANOI TRANSFER · PERSONAL SUPPORT",
    title: "LUXURY HA LONG CRUISES",
    subtitle: "Exceptional journeys through Ha Long & Lan Ha Bay",
    description: "Handpicked 5-star cruises paired with private luxury chauffeur transfers from Hanoi. Personalized service, transparent pricing, and direct WhatsApp assistance.",
    usps: [
      { icon: "diamond", label: "Handpicked Cruises" },
      { icon: "van", label: "Private 7-Seat Transfer" },
      { icon: "support", label: "Direct Support" },
      { icon: "star", label: "Best Available Options" },
    ],
  },
  cruises: [
    {
      id: "paradise-elegance",
      name: "Paradise Elegance",
      bay: "Ha Long Bay",
      locationBadge: "Ha Long Bay",
      durations: "2 Days 1 Night · 3 Days 2 Nights",
      rating: 4.9,
      reviewsCount: 312,
      priceVnd: "5,800,000",
      imageKey: "paradiseElegance",
      tagline: "Classic modern elegance with private sundeck balconies",
    },
    {
      id: "orchid-premium",
      name: "Orchid Premium Cruise",
      bay: "Lan Ha Bay",
      locationBadge: "Lan Ha Bay",
      durations: "2 Days 1 Night · 3 Days 2 Nights",
      rating: 4.8,
      reviewsCount: 275,
      priceVnd: "6,250,000",
      imageKey: "orchidPremium",
      tagline: "Intimate boutique luxury navigating pristine secluded waters",
    },
    {
      id: "athena-luxury",
      name: "Athena Luxury Cruise",
      bay: "Ha Long Bay",
      locationBadge: "Ha Long Bay",
      durations: "2 Days 1 Night · 3 Days 2 Nights",
      rating: 4.9,
      reviewsCount: 194,
      priceVnd: "6,800,000",
      imageKey: "athenaLuxury",
      tagline: "Sophisticated styling, panoramic jacuzzi and gourmet dining",
    },
    {
      id: "heritage-binh-chuan",
      name: "Heritage Binh Chuan",
      bay: "Lan Ha Bay",
      locationBadge: "Lan Ha Bay",
      durations: "2 Days 1 Night · 3 Days 2 Nights",
      rating: 4.8,
      reviewsCount: 232,
      priceVnd: "5,600,000",
      imageKey: "heritageBinhChuan",
      tagline: "Indochine heritage masterpiece with curated art & culture",
    },
    {
      id: "stellar-of-the-seas",
      name: "Stellar of the Seas",
      bay: "Ha Long Bay",
      locationBadge: "Ha Long Bay",
      durations: "2 Days 1 Night · 3 Days 2 Nights",
      rating: 4.9,
      reviewsCount: 221,
      priceVnd: "7,200,000",
      imageKey: "stellarSeas",
      tagline: "Superyacht with circular deck swimming pool and wine cellar",
    },
    {
      id: "era-cruises",
      name: "Era Cruises",
      bay: "Lan Ha Bay",
      locationBadge: "Lan Ha Bay",
      durations: "2 Days 1 Night · 3 Days 2 Nights",
      rating: 4.8,
      reviewsCount: 187,
      priceVnd: "6,400,000",
      imageKey: "eraCruises",
      tagline: "Ultra-spacious luxury ocean-view suites with private jacuzzis",
    },
  ],
  preferenceCategories: [
    {
      id: "couples",
      title: "Couples",
      icon: "heart",
      desc: "Romantic getaways, private balcony suites, candlelit dining & sunset champagne",
    },
    {
      id: "family",
      title: "Family",
      icon: "family",
      desc: "Interconnecting family suites, kid-friendly activities, kayaking & cooking class",
    },
    {
      id: "luxury",
      title: "Luxury Experience",
      icon: "diamond",
      desc: "5-star superyacht facilities, sundeck pools, spa treatments & fine wine cellars",
    },
    {
      id: "scenic",
      title: "Scenic Journey",
      icon: "mountains",
      desc: "Tranquil Lan Ha & Bai Tu Long routes away from crowds into untouched lagoons",
    },
  ],
  seamlessTransfer: {
    heading: "From Your Hotel to Your Cruise — Seamlessly",
    subtitle: "Enjoy a private journey from Hanoi or Noi Bai Airport directly to your cruise terminal.",
    steps: [
      { label: "Hanoi Hotel", icon: "hotel" },
      { label: "Private Hoang Luxury Vehicle", icon: "van" },
      { label: "Ha Long / Tuan Chau Port", icon: "anchor" },
      { label: "Luxury Cruise", icon: "cruise" },
    ],
    features: [
      { label: "Door-to-door pickup", icon: "pin" },
      { label: "Private 7-Seat vehicle", icon: "seat" },
      { label: "Flexible departure time", icon: "clock" },
      { label: "Luggage assistance", icon: "luggage" },
    ],
  },
  experiences: {
    heading: "More Than a Night on the Bay",
    description: "Wake up surrounded by limestone islands, savor refined dining, explore hidden caves and create unforgettable memories in one of the world's most extraordinary landscapes.",
    items: [
      { id: "cabin", label: "Luxury Cabin", imageKey: "expCabin" },
      { id: "dining", label: "Fine Dining", imageKey: "expDining" },
      { id: "sunset", label: "Sunset Experience", imageKey: "expSunset" },
      { id: "activities", label: "Bay Activities", imageKey: "expKayaking" },
    ],
  },
  durations: [
    {
      title: "2 DAYS · 1 NIGHT",
      subtitle: "The essential Ha Long experience",
      imageKey: "paradiseElegance",
      highlights: ["Overnight on bay", "Cave exploration", "Sunset sundeck party", "Morning Tai Chi"],
    },
    {
      title: "3 DAYS · 2 NIGHTS",
      subtitle: "More time to explore the bay",
      imageKey: "orchidPremium",
      highlights: ["Deep Lan Ha Bay lagoon", "Cycling in Viet Hai village", "Day boat excursion", "Hidden beach swim"],
    },
    {
      title: "PRIVATE / SPECIAL EXPERIENCE",
      subtitle: "For couples, families & private groups",
      imageKey: "heritageBinhChuan",
      highlights: ["Exclusive private charter", "Tailored daily itinerary", "Dedicated personal butler", "Private beach dining"],
    },
  ],
  stats: {
    heading: "A More Personal Way to Experience Ha Long",
    benefits: [
      "Expert cruise recommendation",
      "Private transfer coordination",
      "Cruise terminal assistance",
      "Direct WhatsApp support",
    ],
    metrics: [
      { value: "12,686+", label: "Successful Transfers", icon: "group" },
      { value: "20+", label: "Countries Served", icon: "globe" },
      { value: "4.9 / 5", label: "Guest Rating", icon: "star" },
      { value: "24/7", label: "Travel Support", icon: "headset" },
    ],
  },
  moments: [
    { imageKey: "heroHalong", title: "Limestone Panorama" },
    { imageKey: "expCabin", title: "Luxury Suite View" },
    { imageKey: "expDining", title: "Gourmet Dinner" },
    { imageKey: "expKayaking", title: "Emerald Kayaking" },
  ],
  reviews: [
    {
      stars: 5,
      text: "Perfect from start to finish! The private transfer was on time, very comfortable, and the cruise exceeded our expectations. Highly recommended!",
      name: "Jessica M.",
      country: "Australia",
      avatarLetter: "J",
    },
    {
      stars: 5,
      text: "We booked cruise and transfer together with Hoang Luxury Travel. Everything was smooth and easy. 5-star service!",
      name: "David & Sarah",
      country: "United Kingdom",
      avatarLetter: "D",
    },
    {
      stars: 5,
      text: "Amazing experience in Ha Long Bay. The transfer was excellent and the staff supported us on WhatsApp 24/7.",
      name: "Marco R.",
      country: "Italy",
      avatarLetter: "M",
    },
  ],
  faqs: [
    {
      q: "Which cruise should I choose?",
      a: "It depends on your travel style! For modern luxury with infinity pools, we recommend Stellar of the Seas. For romantic couples and Lan Ha Bay tranquility, Orchid Premium or Heritage Binh Chuan are exceptional. Contact us on WhatsApp for a personalized recommendation tailored to your budget and travel dates.",
    },
    {
      q: "Can I book cruise and private transfer together?",
      a: "Yes, absolutely! We specialize in combined packages where your private luxury chauffeur picks you up directly at your Hanoi hotel or Noi Bai Airport, takes you straight to the correct cruise lounge in Ha Long / Tuan Chau / Hai Phong, and brings you back after disembarkation.",
    },
    {
      q: "Is hotel pickup included?",
      a: "When you book your private transfer with Hoang Luxury Travel, door-to-door pickup from any hotel in Hanoi Old Quarter, West Lake, or Noi Bai Airport is fully coordinated with your cruise departure time.",
    },
    {
      q: "Where do cruises depart from?",
      a: "Cruises depart from Tuan Chau International Port (Ha Long Bay cruises) or Ha Long International Cruise Port (Sun Group Port), and Got Pier / Tuan Chau for Lan Ha Bay cruises. Your driver will drop you directly at your specific cruise check-in lounge.",
    },
    {
      q: "What is included in the cruise price?",
      a: "Cruise rates typically include luxury en-suite cabin accommodation, all onboard gourmet meals (lunch, dinner, breakfast, brunch), bay excursions (kayaking, cave visits, bamboo boats, swimming), entrance & sightseeing fees, and English-speaking tour guide onboard.",
    },
    {
      q: "What happens after I request availability?",
      a: "Our dedicated travel consultant will instantly check live cabin availability with the cruise management, confirm the best rate, provide itinerary details, and coordinate your private chauffeur pickup schedule via WhatsApp or email.",
    },
  ],
};
